name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Release Please
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: GoogleCloudPlatform/release-please-action@v4
        with:
          release-type: "node"
